import { ThemeProvider, BaseStyles } from "@primer/react";
import "./primer.scss";

export const metadata = {
    title: "Rundocs - DEV",
    description: "Generated by NEXT",
}

export default function RootLayout({ children }) {
    const colorMode = "auto";
    const dayScheme = "light";
    const nightScheme = "dark_dimmed";
    return (
        <html
            data-color-mode={colorMode}
            data-light-theme={dayScheme}
            data-dark-theme={nightScheme}
            suppressHydrationWarning
        >
            <body>
                <ThemeProvider
                    colorMode={colorMode}
                    dayScheme={dayScheme}
                    nightScheme={nightScheme}
                    preventSSRMismatch
                >
                    <BaseStyles>
                        {children}
                    </BaseStyles>
                </ThemeProvider>
            </body>
        </html>
    );
}
