import "./primer.scss";

export const metadata = {
    title: "Rundocs - DEV",
    description: "Generated by NEXT",
}

export default function RootLayout({ children }) {
    return (
        <html
            data-color-mode="auto"
            data-light-theme="light"
            data-dark-theme="dark_dimmed"
        >
            <body>
                {children}
            </body>
        </html>
    );
}
